### ISSUE TITLE
Unable to build project due to signing issue with SwiftGMP on Mac

### ISSUE THREAD

**Issue by jeffd** [ipfs/swift-ipfs-api#1]
I'm trying to embed your framework, but get the code signing error below. I saw you recently removed code signing for that project. Any workarounds for this issue?

    /Contents/Frameworks/SwiftGMP.framework/Versions/A: code object is not signed at all
    In subcomponent: Contents/Frameworks/SwiftGMP.framework/Versions/A/Frameworks/GMPLib/gmp-iPhoneOS.h
    Command /usr/bin/codesign failed with exit code 1

**Comment by NeoTeo** [comment]
Hi Jeffd. Thanks for your message.

I'm wondering if you are missing something in the way you set up your project.. Have a look at https://github.com/NeoTeo/SwiftBase58 for an example of a project that successfully embeds SwiftGMP and compare it with your own settings.

:) Teo

**Comment by jeffd** [comment]
Disabling code signing worked, but why do you disable it in the first place?

**Comment by NeoTeo** [comment]
Good to hear you got it working. I disabled it because, to be honest, I haven't yet understood the benefits/reasons for doing so. Simpler to just leave it out for now.
