### ISSUE TITLE
Can I access the node on other computers?

### ISSUE THREAD

**Issue by W-B-S** [ipfs/swift-ipfs-api#10]
let api = try IpfsApi(host: "127.0.0.1", port: 5001)
Can I change the host from local ip address to a public ip of over aws server running ipfs node?
thanks

**Comment by NeoTeo** [comment]
As long as the address:port is accessible it should work. 
You can test it via a browser or the ipfs command line first.
See also APIary for api strings in the browser: https://ipfs.docs.apiary.io/#reference/add
