### ISSUE TITLE
is bug?

### ISSUE THREAD

**Issue by xuruijing** [ipfs/swift-ipfs-api#14]
public func peers(_ completionHandler: @escaping ([Multiaddr]) throws -> Void) throws {
        try parent!.fetchJson("swarm/peers?stream-channels=true") {
            result in
            
            var addresses: [Multiaddr] = []
            if let swarmPeers = result.object?["Strings"]?.array {
                /// Make an array of Multiaddr from each peer in swarmPeers.
                addresses = try swarmPeers.map { try newMultiaddr($0.string!) }
            }
            
            /// convert the data into a Multiaddr array and pass it to the handler
            try completionHandler(addresses)
        }
    }

have not this key -->"object?["Strings"]".   is "object?["Peers"]"?

**Comment by NeoTeo** [comment]
It is! Thank you for catching that :) I'll credit you in the commit message. 
A good example of why it's bad to rely on Stringly Typed indexing.
