### ISSUE TITLE
carthage update failed

### ISSUE THREAD

**Issue by xuruijing** [ipfs/swift-ipfs-api#16]
*** Checking out SwiftMultiaddr at "v0.2.1"
*** xcodebuild output can be found in /var/folders/v5/5sj60y654qx6933php_fb5s00000gn/T/carthage-xcodebuild.RAZXuF.log
*** Building scheme "SwiftGMP" in SwiftGMP.xcodeproj
*** Building scheme "SwiftHex" in SwiftHex.xcodeproj
*** Building scheme "SwiftBase58" in SwiftBase58.xcodeproj
*** Building scheme "SwiftMultihash" in SwiftMultihash.xcodeproj
*** Building scheme "VarInt" in VarInt.xcodeproj
*** Building scheme "SwiftMultiaddr" in SwiftMultiaddr.xcodeproj
*** Building scheme "SwiftIpfsApi" in SwiftIpfsApi.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xuruijing/MyWork/IPFS_API/swift-ipfs-api-master/Carthage/Checkouts/swift-ipfs-api/SwiftIpfsApi.xcodeproj -scheme SwiftIpfsApi -configuration Release -derivedDataPath /Users/xuruijing/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/swift-ipfs-api/1408e06ccc188cf31348a7e5cb259bf19395be37 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/v5/5sj60y654qx6933php_fb5s00000gn/T/swift-ipfs-api SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xuruijing/MyWork/IPFS_API/swift-ipfs-api-master/Carthage/Checkouts/swift-ipfs-api)

**Comment by NeoTeo** [comment]
I suspect an old Carthage version or possibly pebcak.
