### ISSUE TITLE
Multipart.swift finishMultipart exception is not thrown.

### ISSUE THREAD

**Issue by baquedano** [ipfs/swift-ipfs-api#23]
Hi, There's a problem with Multipart.swift line 158, the exception was just printed out instead of being thrown (the throw is commented out) so I'm unable to handle the exception and end up having a loader screen stuck.

Only get this printed out instead: 

Task <698420E9-94EC-4F7F-9F2D-0F16AFB77E7A>.<1> finished with error - code: -1001
Error in dataTaskWithRequest: Optional(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x280492b50 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://ipfs.infura.io:5001/api/v0/add?stream-channels=true, NSErrorFailingURLKey=https://ipfs.infura.io:5001/api/v0/add?stream-channels=true, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.})

**Comment by NeoTeo** [comment]
Hi @baquedano . The reason I don't throw is that the API method is async so it wouldn't work. 
For now I'll patch this by passing an empty Data that the completion handler can check for.
In Swift 5, which should be final soon, we get the Result type which I'll use to pass back instead.

Thanks for reporting this.
