### ISSUE TITLE
How to run the IPFS daemon on a real iOS device like iPhone?

### ISSUE THREAD

**Issue by AbhiSNSoft** [ipfs/swift-ipfs-api#27]
I got it working with the IPFS daemon running on a mac command line and simulator but how to achieve this on a real iOS device(iPhone or iPad)?

**Comment by NeoTeo** [comment]
This is not the IPFS daemon. It is a native client of an existing daemon through its API. To run the client on iOS, have a look at https://github.com/NeoTeo/IpfsIosAppExample. I've not tried it for a very long time so ymmv.
