### ISSUE TITLE
swift example error

### ISSUE THREAD

**Issue by clivexiang** [ipfs/swift-ipfs-api#4]
import SwiftIpfsApi

/// For brevity we are not catching failed try's. You should.
let api = try! SwiftIpfsApi("127.0.0.1", "5001") 

try! api.id() {
    (idData : JsonType) in
                    
    print("Yay, I've got an id: "+ idData.object?["ID"]?.string)
}

/Users/xiangchunxiao/Desktop/swiipfs/swiipfs/ViewController.swift:19:31: Cannot call value of non-function type 'module<SwiftIpfsApi>'

**Comment by NeoTeo** [comment]
Please have a look at my[ Mac ipfs project](https://github.com/NeoTeo/IpfsMacAppExample) for a working example.
